spring:
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    org.ohmyopensource: DEBUG
    org.testcontainers: INFO